//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBikeStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class wishlist
    {
        public int id { get; set; }
        public int p_id { get; set; }
        public int u_id { get; set; }
        public string p_name { get; set; }
        public Nullable<decimal> p_price { get; set; }
        public string url { get; set; }
    
        public virtual user user { get; set; }
        public virtual product product { get; set; }
    }
}
